name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  one:
    name: one
    runs-on: ubuntu-latest 
    steps:
    - name: step one one
      uses: actions/checkout@v2
    - name: step one two 
      run: env | sort
